Welcome
Welcome to the second part of our course. In the previous part, we learned how to calculate the total revenue in a given period. Today, we're going to take a look at different ways to compare revenue values across different periods.

In this part, we'll learn how to create three types of revenue reports.

First, we'll talk about reports with total revenue for multiple periods of time, for example total revenue in each month of each year:

month	revenue
...	...
2016-12-01 00:00:00	128355.40
2017-01-01 00:00:00	138288.95
2017-02-01 00:00:00	143177.03
...	...
This report allows you to see trends in the revenue: if it's generally increasing, decreasing or staying at the same level.

Next, we'll learn how to extend these reports with information about the change (delta) between consecutive periods:

month	revenue	delta (%)
...	...	...
2016-12-01 00:00:00	128355.40	-2.15
2017-01-01 00:00:00	138288.95	7.74
2017-02-01 00:00:00	143177.03	3.53
...	...	...
This report gives you quantitative information about the change rate between periods.

Finally, we'll learn how to create a revenue-in-quarters report. quarters are three-month periods of time, the first quarter is a period from January to March, the second quarter is a period from April to June, etc. quarterly analysis is a commonly used financial analysis. The report looks like this, with rows representing years and columns representing quarters:

year	Q1	Q2	Q3	Q4
2016	0.00	0.00	79728.58	128355.40
2017	138288.95	143177.03	153937.78	181681.45
2018	298491.57	142132.33	0.00	0.00
Such reports can help us see seasonal trends in revenue values. For instance, Q4 revenues are typically higher because of holiday shopping. It would be much harder to spot such trends when quarters are shown below each other.

Are you ready to learn more about analyzing revenue trends?
